### ISSUE TITLE
Menu collapse is not working

### ISSUE THREAD

**Issue by rita3ko** [cloudflare/workers-docs#830] opened 2020-05-21 23:42 UTC
I currently cannot collapse sections of the left-hand side menu. 
Example: 
<img width="298" alt="Screen Shot 2020-05-21 at 4 40 31 PM" src="https://user-images.githubusercontent.com/2414910/82616399-ee573300-9b81-11ea-81b8-17699f8424bb.png">

Clicking on the arrow next to Tooling, Wrangler CLI, Configuration doesn't do anything. It just stays open. The only way to collapse it is by opening up another section (e.g. Workers Sites).

**Comment by ispivey** [comment] 2020-05-22 13:11
I was able to reproduce. This is likely caused by one of the dependency upgrades that @victoriabernard92 and I both merged yesterday.

@victoriabernard92 do you have some time to take a look today? If the cause isn't obvious to you, and we can repro locally, the easiest thing might be to `git bisect` back a day to figure out which dependency update caused this.

**Comment by victoriabernard92** [comment] 2020-05-26 16:32
This never actually uncollapsed. Long ago, we had a design that had no arrows or collapsing. See https://developers.cloudflare.com/gateway/locations/ for example. @adamschwartz as a quick fix to the massive number of nav items, added the auto-collapsing but never uncollapsing with the intention of this being temporary. Correct me if i am misremembering there Adam!

We have a few options moving forward:
* add the collapsing functionality it by adding a `collapse` field in `SidebarItem.tsx` this is some work that will be overwritten by the nav bars redesign
* design the CSS in a way that users won't assume the ability to uncollapse
* Wait to fix this in the redesign

**Comment by adamschwartz** [comment] 2020-05-26 20:51
I agree that the current design is confusing, but this has been the behavior of the Hugo-powered Cloudflare docs since it first existed (so for at least the last two years).

Here are a few other examples on other Hugo-powered Cloudflare docs:

https://developers.cloudflare.com/mobile-sdk/getting_started/ios/

![image](https://user-images.githubusercontent.com/154613/82947745-7e282300-9f6e-11ea-827e-1abd6cb6d621.png)

https://developers.cloudflare.com/internet/protocols/

![image](https://user-images.githubusercontent.com/154613/82947860-b6c7fc80-9f6e-11ea-85c6-319afaca30bb.png)

https://developers.cloudflare.com/ssl/custom-certificates/

![image](https://user-images.githubusercontent.com/154613/82947917-d3643480-9f6e-11ea-86fe-380db4354f7f.png)

In each of these three examples, clicking the arrow inside the orange-highlighted nav row will only navigate to the current page (in effect, refreshing the page) rather than collapsing its respective subnav section.

What’s unique to the Workers docs is that the arrow design was changed, putting the arrow to the left side of the nav text label, and the arrow directions signaling “Closed”/“Opened” changed from Down/Up to Right/Down.

I made these design changes per request of the Workers team at the time since they felt like the side nav design was limiting their ability to add new content to the docs. I believe part of the reason they felt this way was because some members of the team weren’t aware that frontmatter properties [could be used](https://github.com/cloudflare/workers-docs/commit/82f003c5edd12b827ac70cfa95ccf6c95f5329bd) to set expand/collapse arrows up _at all_, but I believe that some other members of the team were aware of that feature, but chose not to take advantage of it due to the original design (with the arrows on the right side of the text) being even more confusing.

So as a temporary stopgap (as @victoriabernard92 noted) I [set the pages with subnavs use `alwaysopen: false`](https://github.com/cloudflare/workers-docs/commit/82f003c5edd12b827ac70cfa95ccf6c95f5329bd), [redesigned the top nav](https://github.com/cloudflare/workers-docs/commit/5b09c87a6f4458997f205ff6ec8a1134944e03fd), and [updated the cloudflare-hugo-docs version](https://github.com/cloudflare/workers-docs/commit/1f139e0492407054746985fd177ef1dc57281bfb)
 to take advantage of the new CSS arrow design.

The redesign completely addresses all of these issues, with separate click targets for the arrow and the nav item itself, there can be little confusion.

| Button  | Nav item |
| --------| -------- |
| ![image](https://user-images.githubusercontent.com/154613/82949015-e37d1380-9f70-11ea-876d-6fafeadeeaaf.png) | ![image](https://user-images.githubusercontent.com/154613/82949029-e841c780-9f70-11ea-9e6c-c74eaeb43b1c.png) |

**Comment by adamschwartz** [comment] 2020-07-23 08:17
Marking this as wontfix since this will be fixed in the new docs.

**Closed** 2020-07-23 08:17 UTC
Labels: bug, needs design, tech, wontfix
